services:
  disparaai:
    image: joaopella/disparaai:1.0.0    
    environment:
      - DATABASE_URL=postgresql://disparaai:disparaai123@postgres_postgres:5432/disparaai

      - EVOLUTION_API_URL=${EVOLUTION_API_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - EVOLUTION_INSTANCE_NAME=${EVOLUTION_INSTANCE_NAME}

      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

      - PORT=8000
      - DEBUG=false
      - LOG_LEVEL=info
      - TESTING_MODE=${TESTING_MODE:-false}
      - TEST_OWNER_PHONE=${TEST_OWNER_PHONE}

      - WEBHOOK_URL=${WEBHOOK_URL}
      - WHATSAPP_WEBHOOK_TOKEN=${WHATSAPP_WEBHOOK_TOKEN}

      - MAX_FILE_SIZE_MB=10

    networks:
      - 4SNetwork
      
    volumes:
      - disparaai_app_logs:/app/logs

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=4SNetwork"
        - "traefik.http.routers.disparaai-http.rule=Host(`disparaai.4scale.com.br`)"
        - "traefik.http.routers.disparaai-http.entrypoints=web"
        - "traefik.http.routers.disparaai-http.middlewares=https-redirect@file"
        - "traefik.http.routers.disparaai-https.rule=Host(`disparaai.4scale.com.br`)"
        - "traefik.http.routers.disparaai-https.entrypoints=websecure"
        - "traefik.http.routers.disparaai-https.tls=true"
        - "traefik.http.routers.disparaai-https.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.disparaai-service.loadbalancer.server.port=8000"

volumes:
  disparaai_app_logs:
    driver: local

networks:
  4SNetwork:
    external: true
